runtime: nodejs18
instance_class: F2
service: book-matching

handlers:
- url: /.*
  script: auto

# Secure (HTTPS) configuration
- url: /.*
  script: auto
  secure: always

env_variables:
  PORT: 8080


entrypoint: node ./server.js


