steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/fluency-403011/book-matching', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/fluency-403011/book-matching']

  # Deploy the container to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'book-matching'
      - '--image=gcr.io/fluency-403011/book-matching'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--region=us-east1'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1'
      - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
